### ISSUE TITLE
Requests sometimes take up to 10 seconds

### ISSUE THREAD

**Issue by jhoelzl** [azwyane/apicovid2019#1]
Maybe because also the main site https://www.worldometers.info/coronavirus/ is slow at this time?
I tested Heroku and Azure version.

So just an idea: Would be nice if you could cache some data, so maybe save every 10min one version of the json on your local server, an when the main site is slow (maybe slower than 3 seconds), use the cached data instead.

Regards,
Josef

**Comment by azwyane** [comment]
Hello Josef,
Thank you for using the api and making your review. This api was made with a concept to update data very fast as it updates parallely with worldometers. In previous version I had cache with saving it in a file decreasing the output time of api but since I required to have latest info than anyother I made each request uncaching. 
For now as a solution of large response time, you can cache the response of Api call in your own project.
Also I am considering your invaluable view and making possible decrease in response time.

Regards,
Azwane

**Comment by azwyane** [comment]
Azure and heroku takes varyingly about 10 to 15 sec on being idle for long time but on continuous request I have encountered about only 3 sec response which is prettly good. I guess the place I have hosted on takes lil bit of time to start from sleep. Still you can yourself cache the response.

**Comment by jhoelzl** [comment]
Hi, thanks for your response. Okay, i try to cache it on my side!
